### ISSUE TITLE
adding disk vax nbsd 6.1.5

### ISSUE THREAD

**Issue by TheFausap** [jguillaumes/dockersimh#1]
Hello 
i'm trying to enable a new controller in the vax configuration (rqb), and attach a new disk, but when the system starts, I cannot see the new disk.

Do I have to recompile the kernel ? 

thanks,
Fausto

**Comment by jguillaumes** [comment]
I don't think so. NetBSD should see it right away. Have you tried it out of docker? (ie, in a non-containerized environment)

**Comment by TheFausap** [comment]
I tried but the result is the same. I enabled rqb controller and attached a disk (rqb0).
The problem is at the bus level: only mscpbus0 and mscpbus1 are recognized.

**Comment by TheFausap** [comment]
Hello i found maybe the problem. In the VAX8600 config file a second UDA50 is defined at address 160334 (octal). But SIMH put the UDA50 for RQB controller at 160354.
So, I'll try to recompile the kernel with this modification and I'll keep you posted about my result.

**Comment by TheFausap** [comment]
I finished compiling kernel. Now it works :-)

**Comment by jguillaumes** [comment]
Great! I’m closing the issue.
Have fun!

**Comment by jguillaumes** [comment]
Additional note: maybe you could open an issue to the upstream project (simh)
